-- MySQL Script generated by MySQL Workbench
-- Fri Jun 11 17:20:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema atleticator
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema atleticator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atleticator` DEFAULT CHARACTER SET utf8 ;
USE `atleticator` ;

-- -----------------------------------------------------
-- Table `atleticator`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atleticator`.`users` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `delete` TINYINT(1) NULL,
  `power` VARCHAR(45) NULL,
  `dataNasc` DATE NULL,
  `profilephoto` VARCHAR(255) NULL,
  `admultimochat` INT NULL,
  PRIMARY KEY (`idUser`));


-- -----------------------------------------------------
-- Table `atleticator`.`associacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atleticator`.`associacao` (
  `assoc_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `user_idUser` INT NOT NULL,
  `idAssoc` VARCHAR(45) NULL,
  `pagamento` TINYINT(1) NULL,
  PRIMARY KEY (`assoc_id`),
  INDEX `fk_category_user_idx` (`user_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_category_user`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `atleticator`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `atleticator`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atleticator`.`news` (
  `news_id` INT NOT NULL AUTO_INCREMENT,
  `img` VARCHAR(255) NOT NULL,
  `htmlinterno` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NULL,
  `delete` TINYINT(1) NULL,
  `data` TIMESTAMP(6) NULL,
  PRIMARY KEY (`news_id`));


-- -----------------------------------------------------
-- Table `atleticator`.`user_has_news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atleticator`.`user_has_news` (
  `user_idUser` INT NOT NULL,
  `news_news_id` INT NOT NULL,
  `new` TINYINT(1) NULL,
  `user_has_new_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`user_has_new_id`),
  INDEX `fk_user_has_news_news1_idx` (`news_news_id` ASC) VISIBLE,
  INDEX `fk_user_has_news_user1_idx` (`user_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_news_user1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `atleticator`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_news_news1`
    FOREIGN KEY (`news_news_id`)
    REFERENCES `atleticator`.`news` (`news_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `atleticator`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atleticator`.`produto` (
  `produto_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `preco` FLOAT NULL,
  `esconder` TINYINT(1) NULL,
  `imagem` VARCHAR(45) NULL,
  PRIMARY KEY (`produto_id`));


-- -----------------------------------------------------
-- Table `atleticator`.`tamanho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atleticator`.`tamanho` (
  `tamanho_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`tamanho_id`));


-- -----------------------------------------------------
-- Table `atleticator`.`cor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atleticator`.`cor` (
  `cor_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cor_id`));


-- -----------------------------------------------------
-- Table `atleticator`.`produto_has_cor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atleticator`.`produto_has_cor` (
  `produto_produto_id` INT NOT NULL,
  `cor_cor_id` INT NOT NULL,
  `produto_has_cor_id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_produto_has_cor_cor1_idx` (`cor_cor_id` ASC) VISIBLE,
  INDEX `fk_produto_has_cor_produto1_idx` (`produto_produto_id` ASC) VISIBLE,
  PRIMARY KEY (`produto_has_cor_id`),
  CONSTRAINT `fk_produto_has_cor_produto1`
    FOREIGN KEY (`produto_produto_id`)
    REFERENCES `atleticator`.`produto` (`produto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_cor_cor1`
    FOREIGN KEY (`cor_cor_id`)
    REFERENCES `atleticator`.`cor` (`cor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `atleticator`.`produto_has_tamanho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atleticator`.`produto_has_tamanho` (
  `produto_produto_id` INT NOT NULL,
  `tamanho_tamanho_id` INT NOT NULL,
  `produto_has_tamanho_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`produto_has_tamanho_id`),
  INDEX `fk_produto_has_tamanho_tamanho1_idx` (`tamanho_tamanho_id` ASC) VISIBLE,
  INDEX `fk_produto_has_tamanho_produto1_idx` (`produto_produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_produto_has_tamanho_produto1`
    FOREIGN KEY (`produto_produto_id`)
    REFERENCES `atleticator`.`produto` (`produto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_tamanho_tamanho1`
    FOREIGN KEY (`tamanho_tamanho_id`)
    REFERENCES `atleticator`.`tamanho` (`tamanho_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `atleticator`.`chatstats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atleticator`.`chatstats` (
  `idtable1` INT NOT NULL AUTO_INCREMENT,
  `buynew` INT NULL,
  `users_idUser` INT NOT NULL,
  `admnew` INT NULL,
  PRIMARY KEY (`idtable1`),
  INDEX `fk_chatstats_users1_idx` (`users_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_chatstats_users1`
    FOREIGN KEY (`users_idUser`)
    REFERENCES `atleticator`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
